name: My First Workflow

# Trigger
on: 
- push

# Jobs
jobs:
  # Job name
  my-first-workflow:
    # OS that this job will be running on
    runs-on: ubuntu-latest

    # List of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"