name: My First Workflow

# Trigger
on: 
- push

# Jobs
jobs:
  # Job name
  my-first-workflow:
    # OS that this job will be running on
    runs-on: ubuntu-latest

    # List of steps to perform task
    steps:
    - name: Echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: Echo information about the context
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}, run number - ${{ github.run_number }}"
    - name: List runner OS
      run: echo "runner OS - ${{ runner.os }}"
    - name: Echo my secret
      run: echo " MY_SECRET is ${{ secrets.MY_SECRET }}"
    - name: List my current directory before checkout
      run: ls -la
    - name: Branch name
      run: echo "branch name - ${{ github.ref_name }}"
    - name: Checkout the current repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: List my current directory after checkout
      run: ls -la